# --- KERNEL POOL CONFIGURATION ---
MAX_KERNELS = 5
MIN_KERNELS = 2
KERNEL_TIMEOUT = 300  # 5 minutes
KERNEL_HEALTH_CHECK_INTERVAL = 30  # 30 seconds
MAX_RETRY_ATTEMPTS = 3
RETRY_BACKOFF_BASE = 2  # exponential backoff base

# --- JUPYTER CONNECTION SETTINGS ---
JUPYTER_WS_URL = "ws://127.0.0.1:8888"
JUPYTER_HTTP_URL = "http://127.0.0.1:8888"

# --- ENHANCED WEBSOCKET SETTINGS ---
WEBSOCKET_TIMEOUT = 600  # 10 minutes for long operations
WEBSOCKET_PING_INTERVAL = 30
WEBSOCKET_PING_TIMEOUT = 10

# --- DIRECTORY CONFIGURATION ---
SHARED_DIR = "/app/uploads"
KERNEL_ID_FILE_PATH = f"{SHARED_DIR}/python_kernel_id.txt"

# --- PLAYWRIGHT ---
PLAYWRIGHT_WS_URL = "ws://127.0.0.1:3000/"
