services:
  litebox-claude:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile.litebox-claude
    image: litebox-claude
    container_name: litebox-claude
    environment:
      - ANTHROPIC_API_KEY
      - LITEBOX_INCLUDE_WORKSPACE=1
      - LITEBOX_WORKSPACE_EXCLUDE_GIT=1
    security_opt:
      - seccomp=unconfined
    volumes:
      - .:/workspace
    working_dir: /workspace
    stdin_open: true
    tty: true
